apiVersion: apps/v1
kind: Deployment

metadata:
  name: word-guessing-game

spec:
  replicas: 1

  selector:
    matchLabels:
      app: word-guessing-game

  template:
    metadata:
      labels:
        app: word-guessing-game

    spec:
      containers:
      - name: word-guessing-game

        image: <ecr url>

        ports:
        - containerPort: 5000

        env:
        - name: SECRET_KEY
          value: "production-secret"

        livenessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 20
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 5
